name: PR on main

permissions:
  contents: write
  pull-requests: write
  id-token: write

on:
  pull_request:
    branches:
      - main
    types: [ opened, reopened, synchronize ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.define-envs.outputs.environments }}
      release-tag: ${{ steps.define-envs.outputs.release-tag }}
      is-release: ${{ steps.define-envs.outputs.is-release }}

    steps:
      - name: Define envs information
        id: define-envs
        run: |
            echo is-release=${{ startsWith(github.head_ref, 'release/') && 'true' || '' }} >> $GITHUB_OUTPUT
            echo environments='${{ startsWith(github.head_ref, 'release/') && vars.RELEASE_ENVIRONMENTS || vars.DEV_ENVIRONMENTS }}' >> $GITHUB_OUTPUT
            echo release-tag=${{ startsWith(github.head_ref, 'release/') && 'last-release' || 'origin/main' }} >> $GITHUB_OUTPUT

  lint-and-run-tests:
    needs: [ prepare ]
    runs-on: ubuntu-latest
    outputs:
        affected-projects: ${{ steps.get-affected-projects.outputs.affected-projects }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install deps
        run: yarn install

      - name: Build app
        run: yarn build

  init-state-app:
    needs: [ lint-and-run-tests, prepare ]
    uses: softkitit/github-actions-terraform/.github/workflows/controller-initialize-terraform-state.yml@main
    strategy:
      matrix:
        environment: ${{ fromJson(needs.prepare.outputs.environments) }}
    with:
      organization: ${{ github.event.repository.owner.login }}
      repository-name: ${{ github.event.repository.name }}
      project-name: ${{ github.event.repository.name }}
      environment: ${{ matrix.environment }}
      terraform-folder: terraform
    secrets: inherit

  plan-app:
    needs: [lint-and-run-tests, init-state-app, prepare]
    strategy:
      matrix:
        environment: ${{ fromJson(needs.prepare.outputs.environments) }}
    uses: softkitit/github-actions-terraform/.github/workflows/ci-terraform-plan-and-format.yml@main
    with:
      environment: ${{ matrix.environment }}
      terraform-folder: terraform
      override-plan-comment: false
    secrets: inherit


